from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from pathlib import Path

from app.config import Settings
from app.db import connect, initialize_database
from app.rerank import rerank_latest_retrieval


@dataclass(frozen=True)
class WeeklyRecommendation:
    module: str
    title: str
    author: str | None
    summary: str | None
    goodreads_rating: float | None
    goodreads_rating_checked_at: str | None
    source_url: str | None
    why_recommended: str


def generate_weekly_recommendations(settings: Settings) -> list[WeeklyRecommendation]:
    initialize_database(settings)
    reranked = rerank_latest_retrieval(settings, top_n=5)
    selected: list[WeeklyRecommendation] = []
    seen_titles: set[str] = set()

    for module in sorted({item.module for item in reranked}):
        for item in [candidate for candidate in reranked if candidate.module == module]:
            book = load_book_by_vector_id(settings, item.vector_id)
            if not book or book["status"] != "candidate":
                continue
            title_key = (book["title"] or "").strip().lower()
            if title_key in seen_titles or was_recommended_before(settings, book["title"]):
                continue
            seen_titles.add(title_key)
            selected.append(
                WeeklyRecommendation(
                    module=module,
                    title=book["title"],
                    author=book["author"],
                    summary=book["summary"],
                    goodreads_rating=book["goodreads_rating"],
                    goodreads_rating_checked_at=book["goodreads_rating_checked_at"],
                    source_url=book["source_url"],
                    why_recommended=humanize_reason(book, item.reason),
                )
            )
            break

    save_recommendations(settings, selected)
    write_weekly_markdown(settings, selected)
    write_evaluation_metrics(settings, selected)
    return selected


def humanize_reason(book, scoring_reason: str) -> str:
    themes = book["themes"] or "the themes in your taste profile"
    summary = book["summary"] or "its profile"
    source_note = " It has a source link ready for verification." if book["source_url"] else ""
    rating_note = (
        f" Goodreads rating was checked as {book['goodreads_rating']}."
        if book["goodreads_rating"] is not None
        else " Goodreads rating still needs verification."
    )
    return (
        f"Selected because it matches {themes}. {summary}"
        f"{source_note}{rating_note} Scoring notes: {scoring_reason}"
    )


def load_book_by_vector_id(settings: Settings, vector_id: str):
    with connect(settings) as conn:
        return conn.execute(
            """
            SELECT b.*
            FROM book_chunks c
            JOIN books b ON b.id = c.book_id
            WHERE c.vector_id = ?
            LIMIT 1
            """,
            (vector_id,),
        ).fetchone()


def was_recommended_before(settings: Settings, title: str) -> bool:
    today = date.today().isoformat()
    with connect(settings) as conn:
        row = conn.execute(
            """
            SELECT 1
            FROM recommendations
            WHERE lower(title) = lower(?)
              AND date_added <> ?
            LIMIT 1
            """,
            (title, today),
        ).fetchone()
    return row is not None


def save_recommendations(settings: Settings, recommendations: list[WeeklyRecommendation]) -> None:
    today = date.today().isoformat()
    with connect(settings) as conn:
        conn.execute(
            """
            DELETE FROM recommendations
            WHERE date_added = ?
              AND notes = 'Generated by weekly recommendation pipeline.'
            """,
            (today,),
        )
        for rec in recommendations:
            conn.execute(
                """
                INSERT INTO recommendations (
                    date_added, module, title, author, summary, goodreads_rating,
                    goodreads_rating_checked_at, status, why_recommended, source_url, notes
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, 'recommended', ?, ?, ?)
                """,
                (
                    today,
                    rec.module,
                    rec.title,
                    rec.author,
                    rec.summary,
                    rec.goodreads_rating,
                    rec.goodreads_rating_checked_at,
                    rec.why_recommended,
                    rec.source_url,
                    "Generated by weekly recommendation pipeline.",
                ),
            )


def write_weekly_markdown(settings: Settings, recommendations: list[WeeklyRecommendation]) -> Path:
    settings.outputs_dir.mkdir(parents=True, exist_ok=True)
    today = date.today().isoformat()
    path = settings.outputs_dir / "weekly_recommendations.md"
    lines = [f"# Weekly Book Recommendations - {today}", ""]
    if not recommendations:
        lines.append("No candidate recommendations were selected.")
    for rec in recommendations:
        rating = (
            f"{rec.goodreads_rating} checked {rec.goodreads_rating_checked_at}"
            if rec.goodreads_rating is not None
            else "Goodreads rating pending verification"
        )
        lines.extend(
            [
                f"## {rec.module.replace('_', ' ').title()}",
                "",
                f"**{rec.title}** by {rec.author or 'unknown'}",
                "",
                rec.summary or "Summary pending.",
                "",
                f"- Goodreads: {rating}",
                f"- Source: {rec.source_url or 'pending'}",
                f"- Why: {rec.why_recommended}",
                "",
            ]
        )
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_evaluation_metrics(settings: Settings, recommendations: list[WeeklyRecommendation]) -> None:
    run_id = f"weekly-{date.today().isoformat()}"
    enabled_modules = count_enabled_modules(settings)
    module_coverage = len({rec.module for rec in recommendations}) / enabled_modules if enabled_modules else 0.0
    missing_rating = sum(1 for rec in recommendations if rec.goodreads_rating is None)
    missing_source = sum(1 for rec in recommendations if not rec.source_url)
    with connect(settings) as conn:
        metrics = [
            ("module_coverage", module_coverage, "Share of enabled modules with a selected recommendation."),
            ("recommendation_count", float(len(recommendations)), "Number of selected recommendations."),
            ("missing_goodreads_rating_count", float(missing_rating), "Recommendations needing Goodreads rating verification."),
            ("missing_source_count", float(missing_source), "Recommendations without a source URL."),
        ]
        for name, value, notes in metrics:
            conn.execute(
                """
                INSERT INTO evaluation_results (run_id, metric_name, metric_value, notes)
                VALUES (?, ?, ?, ?)
                """,
                (run_id, name, value, notes),
            )


def count_enabled_modules(settings: Settings) -> int:
    with connect(settings) as conn:
        return int(
            conn.execute(
                "SELECT count(*) FROM recommendation_modules WHERE weekly_enabled = 1"
            ).fetchone()[0]
        )
